name: pathfinder_indoor_navigation
description: "# The following line prevents the package from being accidentally published to"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  provider: ^6.1.2
  searchfield: ^0.8.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_logo.png